{
 "title": "Anova Oven New",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ovenId",
    "label": "Oven ID",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"anova-oven-data\",\n    tag: \"ovenId\",\n    predicate: (r) => true,\n    start: -1d\n)"
   },
   { "name": "bucket", "query": "anova-oven-data" },
   {
    "name": "tempSources",
    "query": "dry, wet, dryTop, dryBottom, probe"
   },
   { "name": "tempUnit", "label": "Temperature Unit", "query": "ºC : C, ºF : F" }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Oven State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"anova-oven-data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state\")\n  |> filter(fn: (r) => r[\"_field\"] == \"mode\")\n  |> filter(fn: (r) => r[\"ovenId\"] == \"${ovenId}\")\n  |> drop(columns: [\"host\", \"ovenId\"])\n  |> sort(columns: [\"_time\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Door",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"door-closed\")\n  |> filter(fn: (r) => r[\"ovenId\"] == \"${ovenId}\")\n  |> drop(columns: [\"host\", \"ovenId\"])\n  |> sort(columns: [\"_time\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Lamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lamp-on\")\n  |> filter(fn: (r) => r[\"ovenId\"] == \"${ovenId}\")\n  |> drop(columns: [\"host\", \"ovenId\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Vent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vent-open\")\n  |> filter(fn: (r) => r[\"ovenId\"] == \"${ovenId}\")\n  |> drop(columns: [\"host\", \"ovenId\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Steam Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"steam-mode\")\n  |> filter(fn: (r) => r[\"ovenId\"] == \"${ovenId}\")\n  |> drop(columns: [\"host\", \"ovenId\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Probe",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"probe-connected\")\n  |> filter(fn: (r) => r[\"ovenId\"] == \"${ovenId}\")\n  |> drop(columns: [\"host\", \"ovenId\"])\n  |> sort(columns: [\"_time\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /watts$/)\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 1000.0}))\n  |> integral(unit: 1h)\n  |> duplicate(column: \"_stop\", as: \"_time\")\n\n"
    }
   ]
  },
  {
   "title": "24h Energy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /watts$/)\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 1000.0}))\n  |> integral(unit: 1h)\n  |> duplicate(column: \"_stop\", as: \"_time\")\n\n"
    }
   ]
  },
  {
   "title": "30d Energy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /watts$/)\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 1000.0}))\n  |> integral(unit: 1h)\n  |> duplicate(column: \"_stop\", as: \"_time\")\n\n"
    }
   ]
  },
  {
   "title": "Timer Set",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"timer-current\" or r[\"_field\"] == \"timer-inital\")\n  |> filter(fn: (r) => r[\"ovenId\"] == \"${ovenId}\")\n  |> drop(columns: [\"host\", \"ovenId\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Oven Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /watts$/)\n  |> drop(columns: [\"host\", \"ovenId\", \"_measurement\"])\n  |> sort(columns: [\"_time\"])\n  |> last()\n"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Temperature ($tempSources)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4.8, "x": 0, "y": 9 },
   "repeat": "tempSources",
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: date.sub(d: 2m, from: v.timeRangeStop), stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"$tempSources\")\n  |> filter(fn: (r) => r[\"ovenId\"] == \"${ovenId}\")\n  |> map(fn: (r) => ({r with _value: if \"${tempUnit}\" == \"F\" then r._value * 1.8 + 32.0 else r._value}))\n  |> drop(columns: [\"host\", \"ovenId\"])\n  |> last()\n\n"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Oven State",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state\")\n  |> filter(fn: (r) => r[\"_field\"] == \"mode\")\n  |> filter(fn: (r) => r[\"ovenId\"] == \"${ovenId}\")\n  |> drop(columns: [\"host\"])\n\n"
    }
   ]
  },
  {
   "title": "Oven Power",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /watts$/)\n  |> filter(fn: (r) => r[\"ovenId\"] == \"${ovenId}\")\n  |> drop(columns: [\"host\", \"ovenId\"])\n\n"
    }
   ]
  },
  {
   "title": "Door",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"door-closed\")\n  |> filter(fn: (r) => r[\"ovenId\"] == \"${ovenId}\")\n  |> drop(columns: [\"host\"])\n\n"
    }
   ]
  },
  {
   "title": "Oven Sensors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"dry\" or r[\"_field\"] == \"dryTop\" or r[\"_field\"] == \"wet\" or r[\"_field\"] == \"dryBottom\" or r[\"_field\"] == \"probe\")\n  |> filter(fn: (r) => r[\"ovenId\"] == \"${ovenId}\")\n  |> map(fn: (r) => ({r with _value: if \"${tempUnit}\" == \"F\" then r._value * 1.8 + 32.0 else r._value}))\n  |> drop(columns: [\"host\", \"ovenId\"])\n\n"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fan-speed\")\n  |> drop(columns: [\"host\", \"ovenId\"])\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"fan-speed\")\n  |> drop(columns: [\"host\", \"ovenId\"])\n"
    }
   ]
  },
  {
   "title": "Humidity and Steam",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"relative-humidity\" or r[\"_field\"] == \"relative-humidity-setpoint\" or r[\"_field\"] == \"steam-percentage-setpoint\")\n  |> filter(fn: (r) => r[\"ovenId\"] == \"${ovenId}\")\n  |> drop(columns: [\"host\", \"ovenId\"])"
    }
   ]
  },
  {
   "title": "Light",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lamp-on\")\n  |> filter(fn: (r) => r[\"ovenId\"] == \"${ovenId}\")\n  |> drop(columns: [\"host\"])\n\n"
    }
   ]
  },
  {
   "title": "Vent",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodes\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vent-open\")\n  |> filter(fn: (r) => r[\"ovenId\"] == \"${ovenId}\")\n  |> drop(columns: [\"host\"])\n\n"
    }
   ]
  }
 ]
}